title: Storytelling Headquarters
author: Jugal Patel
email: jugal@jugal-patel.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for D&D content and helping new DMs get off the ground and running games.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  JugesPatel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
