title: Storytelling Sidebar
author: Jugal Patel
email: jugal@jugal-patel.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for D&D content and helping new DMs run games.

# social links
twitter_username: JugesPatel # DO NOT include the @ character, or else the build will fail!
github_username:  JugesPatel # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true